### ISSUE TITLE
[Announcement] 关于旧版 HyPlayer 的一些计划

### ISSUE THREAD

**Issue by kengwang** [HyPlayer/HyPlayer#398]
目前旧版开发已经到了稳定状态, 已经发布了稳定版本 https://github.com/HyPlayer/HyPlayer/releases/tag/2.1.36.5629
接下来的时间将会将主要精力放在新版开发上.
旧版 HyPlayer 将会成为试验田, 将会把一些神奇的想法放在这里实现 (俗称概念版)
旧版 HyPlayer 将不再关心内存和占用问题, 不再强调稳定性, 而更加强调创意和想法
如果你希望旧版养老的话, 可以收藏旧版安装包并不再接受后续更新 (后续更新都不是强制更新)
如果出现了重大问题也会向养老版本发布更新

下面是正在进行测试的概念版项目: (疯狂画饼)

```[tasklist]
### TODOs
- [ ] https://github.com/HyPlayer/HyPlayer/issues/419
- [ ] Home Page 回退到 210717 版本
```

```[tasklist]
### Done
- [ ] https://github.com/HyPlayer/HyPlayer/issues/410
- [ ] https://github.com/HyPlayer/HyPlayer/pull/469
- [x] 歌词页面动态背景
- [x] 歌词页面动态背景适配 BPM
```
